import type { Metadata } from "next";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Toaster } from "react-hot-toast";
// import { Noto_Sans_KR } from "next/font/google";

// const notoSansKR = Noto_Sans_KR({
//   subsets: ["latin"], // 영문 + 한글
//   variable: "--font-noto-sans-kr", // CSS 변수 이름
//   weight: ["400", "700"],      // 필요하면 가중치 지정
// });

export const metadata: Metadata = {
  title: "Bookmarkase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`font-bookk-light w-full min-h-sc`}>
        <QueryClientProvider client={queryClient}>
          {children}
          <Toaster position="top-center" />
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </body>
    </html>
  );
}
